databases:
  - name: app
    plan: free
    databaseName: app
    user: app

services:
  - type: web
    plan: free
    name: app
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn app.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: app
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4