# Generated by Django 5.0.4 on 2024-04-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_livro_capa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autor",
            name="nome",
            field=models.CharField(max_length=100),
        ),
    ]
