# Generated by Django 5.0.4 on 2024-04-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_autor_nome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoria",
            name="descricao",
            field=models.CharField(max_length=100),
        ),
    ]
