# Generated by Django 5.0.4 on 2024-04-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_categoria_descricao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="editora",
            name="nome",
            field=models.CharField(max_length=100),
        ),
    ]
