# Generated by Django 5.0.6 on 2024-05-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_compra_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tipo_usuario",
            field=models.IntegerField(
                choices=[(1, "Cliente"), (2, "Vendedor"), (3, "Gerente")], default=1, verbose_name="User Type"
            ),
        ),
    ]
