# Generated by Django 5.0.6 on 2024-06-17 11:46

import core.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_compra_tipo_pagamento"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", core.models.user.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="foto",
        ),
        migrations.RemoveField(
            model_name="user",
            name="tipo_usuario",
        ),
        migrations.AddField(
            model_name="user",
            name="passage_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
