# Generated by Django 5.0.6 on 2024-06-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_user_foto_user_tipo_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="passage_id",
            field=models.CharField(default="", max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
