# Generated by Django 5.0.6 on 2024-10-10 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_alter_user_options_alter_livro_autores"),
        ("uploader", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livro",
            name="capa",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="uploader.image",
            ),
        ),
    ]
