# Generated by Django 5.1.3 on 2024-11-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_alter_livro_capa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compra",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Carrinho"), (2, "FINALIZADO"), (3, "Pago"), (4, "Entregue")], default=1
            ),
        ),
    ]
