# Generated by Django 5.2.11 on 2026-03-06 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_itenscompra_livro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='passage_id',
        ),
    ]
